version: '2'
services:
  postgres:
    image: "postgres:10.6"
    container_name: "root-server_postgres_1"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"